blank_issues_enabled: false
contact_links:
  - name: 使用说明 / User Guide
    url: https://rm.byteage.com/zh/docs/getting-started
    about: 怎么用先看这里 | How to use iRightMenu Pro
  - name: 插件开发指南 / Plugin Developer Guide
    url: https://rm.byteage.com/zh/docs/guide
    about: 插件开发相关问题请先查阅 | Check here first for plugin development questions
